general:
  productiveBranch: 'main'

stages:
  Build:
    mtaBuild:
      buildTarget: 'CF'
      applicationPath: '.'
      mtaFilePath: 'mta.yaml'
      applicationName: 'comnartproctravelprocessorapp'